### ISSUE TITLE
Basic design

### ISSUE THREAD

**Issue by schneiderfelipe** [schneiderfelipe/quickcheck#8]
Here's are some points for making it working great:
- We need a concept or type for `Testable` properties
- Functions of many variables representing properties should be reduced recursively on their arguments, which implies some (weak) form of currying
  - This can be accomplished using macros and is currently the biggest bottleneck of the design
  - Two base cases can be implemented, a trivial for `bool` (which is not technically a `Testable` and for single-argument functions.

**Comment by saem** [comment]
Hi, not sure where else to post this, but you're one of the few folks I know who's familiar with property based testing, let alone read the paper, is aware of shrinking, etc... Needless to say, I'm excited. 🎉 

I myself attempted property based testing outside of the compiler in order to test the language (that's a mistake, because the VM has significant restrictions making this pretty useless).

Nonetheless I took an approach more inspired by TypeScript's Fast Check and Kotlin's Kotest libraries, I was a little bit more focused on arbitraries and the ability to create more easily. There are still some gaps in the random data generation (biasing arbitraries to a non-uniform distributinos, the idea being small values and big values tend to be where the interesting bits are).

You can see my attempting hiding inside CPS branch in this repo here: https://github.com/saem/cps/blob/propertytest-refactor/propertytest.nim

**Comment by schneiderfelipe** [comment]
Hi @saem, thanks for your interest and for reaching out! Let me use this issue to explain some of the motivation behind this project, and what I (currently) believe is the future for this package.

In a nutshell, `quickcheck` is meant to (when ready of course)
1. work with `unittests`
2. **fully use the type system** and
3. provide arbitrary default values for *any type* (including `proc`s, `object`s and `tuple`s).

I started writing this because I needed it for other projects. The only option for property-based testing in Nim that I could find was [nim-quicktest](https://github.com/alehander92/nim-quicktest) by @alehander92. But the last commit is 3 years old and the library is somewhat based on ideas from [`hypothesis`](https://hypothesis.works/), a common library for Python. As much as I like `hypothesis`, I feel that it was thought to work nicely with a dynamic language (i.e., no known types at test creation). With Nim, we should be able to leverage the type system and remove the need for the user to specify "strategies" (`hypothesis` analog to arbitraries):

```python
# Example from <https://hypothesis.readthedocs.io/en/latest/quickstart.html#writing-tests>
from hypothesis import given, strategies as st

@given(st.integers(), st.integers())
def test_ints_are_commutative(x, y):
    assert x + y == y + x
```

In Haskell one would do the following with QuickCheck, which takes advantage of the type system and this is what I want to emulate in Nim:

```haskell
import Test.QuickCheck

prop_ints_are_commutative :: Int -> Int -> Bool
prop_ints_are_commutative x y = x + y == y + x

main = quickCheck prop_ints_are_commutative
```

This can be done with `quickcheck` as follows:

```nim
import unittest, quickcheck

check satisfy do (x, y: int) -> bool:
  x + y == y + x
# =>
#   *** Raised! Falsifiable (after 3 quick checks):
# /home/schneider/.choosenim/toolchains/nim-1.4.8/lib/pure/unittest.nim(677) asdf
# /home/schneider/Dropbox/quickcheck/src/quickcheck.nim(211) satisfy
# /home/schneider/Dropbox/quickcheck/src/quickcheck.nim(176) satisfyImpl
# /tmp/asdf.nim(4)         :anonymous
# /home/schneider/.choosenim/toolchains/nim-1.4.8/lib/system/fatal.nim(49) sysFatal
# [[reraised from:
# /home/schneider/.choosenim/toolchains/nim-1.4.8/lib/pure/unittest.nim(677) asdf
# /home/schneider/Dropbox/quickcheck/src/quickcheck.nim(211) satisfy
# /home/schneider/Dropbox/quickcheck/src/quickcheck.nim(74) trigger
# ]]
# Error: unhandled exception: over- or underflow [OverflowDefect]
# Error: execution of an external program failed: '/tmp/asdf '
```

As you can see, the above throws an `OverflowDefect`, and **I (actually) like that**, because this is exactly how the code reads for me: a sum of two arbitrary integers can indeed overflow! Why is that OK in Nim, in my opinion? Because you can use `range`:

```nim
check satisfy do (x, y: range[-1000..1000]) -> bool:
  x + y == y + x
# =>
#   +++ OK, passed 100 quick checks.
```

I see this as a kind of [refinement type](https://en.wikipedia.org/wiki/Refinement_type) (compare with something like [`LiquidHaskell`](https://ucsd-progsys.github.io/liquidhaskell-tutorial/Tutorial_08_Measure_Set.html)).

So one of the key ideas of this library is that *if a function signature can throw an error during testing, it should*. You can actually use `int8` or any other integer type if you want, but the random values are always within the full range of the type ([`quickcheck` uses `rand(int)` under the hood](https://github.com/schneiderfelipe/quickcheck/blob/5b8ca519dd505fb388144a5918c3126f67385bf2/src/quickcheck.nim#L81-L101), as you probably saw). So, instead of specifying strategies, we specify types.

I actually want to go all-in with types:
- **Any** type should work out of the box (currently this does not work with, e.g., objects or tuples). I plan on using compile-time reflection for that.
- Even `proc`s should be able to be randomly generated ([see an old prototype for this](https://github.com/schneiderfelipe/quickcheck/blob/4c5fc6d25ffda721fc35b15f03935a8998955653/src/quickcheck/arbitraries.nim#L40-L48), it's actually simple, but has to be rewritten).
- In the end, `some` is a `proc` and can be overloaded by the user (this has to be tested though, but should work).

> Nonetheless I took an approach more inspired by TypeScript's Fast Check and Kotlin's Kotest libraries, I was a little bit more focused on arbitraries and the ability to create more easily. There are still some gaps in the random data generation (biasing arbitraries to a non-uniform distributinos, the idea being small values and big values tend to be where the interesting bits are).

I opted to (blindly) use `rand` from the [`random` library](https://nim-lang.org/docs/random.html) in all cases. Not sure if that's the right thing, but it's easy:
- for a generic type `T`, the following is attempted, in that order (the first one that compiles is returned):
  - `rand(T)`, which works with integers and ranges
  - `rand(low(T)..high(T))`, which works with floats and enums without holes
- for collections (defined as anything for which `elementType(...)` compiles, produce a random container with up to `rand(uint8)` elements, which works with sequences and strings (I chose `uint8` because it's convenient and we can't use the type system to specify the length).
- support for `array`s has to be rewritten as of now, but it's a trivial implementation, as the size is part of the type (see [an old prototype here](https://github.com/schneiderfelipe/quickcheck/blob/a34b417145245a7e74de3f54b7ccb15dc9b7b2ef/src/quickcheck.nim#L23-L27))

> I did have a scan of your API and I worry about the loss of contextual information informing arbitrary choice, at time of creation and then also during iterations in order to guide the generation/search. I'm sure there is a way to thread that information through when and if required, so not a deal breaker, but this is pretty cool.

Yes, you're right, this has to be fixed (see #13). There was been a major rewrite recently, and this loss of context is recent. The thing is that I wanted to follow QuickCheck and give counter examples as part of the return type. I believe this will lead to a more flexible API in the future, as we could freely post-process results (collecting them, giving labels, making histograms, etc.). Basically, a full monadic API.

> You can see my attempting hiding inside CPS branch in this repo here: https://github.com/saem/cps/blob/propertytest-refactor/propertytest.nim

I like your approach. Do you think we could join forces? Your internals seem to be well ahead of `quickcheck`.

I also want to support `exists`, `existsUnique`, etc. (and make `forAll` the default), similar to how SmallCheck does some stuff, and this seems to be similar to your approach as well.

**Comment by saem** [comment]
I'm on my phone right now, so I'll keep it brief.

First off, I'd be happy to work together.

My goal had been to see if I could get to something like PLT Redex's term generation with PBT, but it's going to be a long road as I've learned, turns out I need core parts of [PLT Redex](https://docs.racket-lang.org/redex/).

Nevertheless, PBT is incredibly useful and I'd love to use it in things like game engine, ECS designs really lend themselves to this.

As far as your approach to types as the descriptions/names of the arbitrary goes that'll work up to a point, then the user will have to do some tricks eventually. Mostly say with what you describe as refinement types, as in adding predicates, which seems akin to clojure specs pre/post conditions. I think it can work, but I have some concerns.

If you'd like more insight into how fast check informed my thinking, don't let the title of this page deceive you, it's more of a design evolution and discussion and it's excellent: https://github.com/dubzzz/fast-check/blob/main/documentation/HowItWorks.md

Especially important is the discussion on shrinking, biasing, context, etc.

BTW, I'm on matrix in the nim channels, CPS, and a few others, are you on the or discord? I'd be happy to chat or even jump on a video/white board/pair program if you'd like.

**Comment by schneiderfelipe** [comment]
@saem Hi Saem, sorry for the late reply. I decided to give up on Nim in general in favor of Rust for most of my projects. As such, this project will be retired, as I'm using [BurntSushi/quickcheck](https://github.com/BurntSushi/quickcheck).
